%%------------------------------------------------------------------------------------%%
%%------------------------------------------------------------------------------------%%
%% Content: Open-Science-Paper LaTeX Scaffold 
%% Usage: Collaborative scientific paper writing %%
%% Author: Claas-Thido Pfaff
%%------------------------------------------------------------------------------------%%
%%------------------------------------------------------------------------------------%%

%%%------------------------------------------------------------------------------%%%
%%% Document class: open_science_paper (Based on Koma-Script: article) %%%
%%%------------------------------------------------------------------------------%%%
%%
%

\documentclass[fontsize=11pt, headings=small, captions=tableheading, pagesize=auto,
DIV=20, notitlepage, final]{subdocuments/open_science_paper}

%%%------------------------------------------------------------------------------%%%
%%% Load user options %%%
%%%------------------------------------------------------------------------------%%%

\usepackage{subdocuments/open_science_paper.sty} 

%%%------------------------------------------------------------------------------%%%
%%% Begin the document %%%
%%%------------------------------------------------------------------------------%%%

\begin{document}

%%%--------------------------------------------------------------%%%
%%% Document preparations %%%
%%%--------------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Preferences for Knitr %%%
%%%-------------------------------------------------%%%

% This code chunk is used to include global Knitr options 
<<global_knitr_options, child='subdocuments/global_knitr_options.Rnw', eval=TRUE>>=
@


%%%--------------------------------------------------------------%%%
%%% Document content %%%
%%%--------------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Include header %%%
%%%-------------------------------------------------%%%

<<subdoc_content_header, child='subdocuments/header.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include abstract %%%
%%%-------------------------------------------------%%%

<<subdoc_content_abstract, child='subdocuments/abstract.Rnw', eval=T>>=
@


% Start 2 column layout %
\begin{multicols}{2}


%%%-------------------------------------------------%%%
%%% Include introduction %%%
%%%-------------------------------------------------%%%

<<subdoc_content_introduction, child='subdocuments/introduction.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include material and methods %%%
%%%-------------------------------------------------%%%

<<subdoc_content_material_methods, child='subdocuments/material_methods.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include results %%%
%%%-------------------------------------------------%%%

<<subdoc_content_results, child='subdocuments/results.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include discussion %%%
%%%-------------------------------------------------%%%

<<subdoc_content_discussion, child='subdocuments/discussion.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include acknowledgements %%%
%%%-------------------------------------------------%%%

<<subdoc_content_acknowledgement, child='subdocuments/acknowledgement.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include the bibliography %%%
%%%-------------------------------------------------%%%

<<options_bibliography, child='subdocuments/options_bibliography.Rnw', eval=T>>=
@


%% End 2 column layout
\end{multicols}


%%%------------------------------------------------------------------------------%%%
%%% End of document %%%
%%%------------------------------------------------------------------------------%%%

\end{document}
