%%%------------------------------------------------------------------------------------%%
%%%------------------------------------------------------------------------------------%%
%%% Content: Open-Science-Paper LaTeX Scaffold 
%%% Usage: Collaborative scientific paper writing 
%%% Author: Claas-Thido Pfaff
%%%------------------------------------------------------------------------------------%%
%%%------------------------------------------------------------------------------------%%

%%%------------------------------------------------------------------------------%%%
%%% Document class: open_science_paper (Based on Koma-Script: article) %%%
%%%------------------------------------------------------------------------------%%%
%%
%

\documentclass[color=false, print=false, csvdata=false, gitinfo=false, linenumbers=false, sectionnumbers=false]{usr/subdocuments/open_science_paper} 

%% Available class options [defaults]
% - color true/[false]: Changes between colored output and a black and white theme 
% - csvdata true/[false]: With csv data enabled you can use the csv file under
%   the data folder to insert title header information into the document.
% - gitinfo true/[false]: Include git information into the title header of the 
%   document. This requires the setup of git hooks which you can do by issuing 
%   the make task (make githooks). After that you need to specify the url of the 
%   git repository inside of the style file and you are done.
% - print true/[false] switches between the color model rgb which is optimal for displays 
%   and the cmyk color model which is required for professional printing. 
% - linenumbers true/[false]: Switch on/off line numbers for the whole document.
% - sectionnumbers true/[false]: Switch between numbered and numberless sections

%%%------------------------------------------------------------------------------%%%
%%% Load user options %%%
%%%------------------------------------------------------------------------------%%%

\input{usr/subdocuments/open_science_paper.sty} 

%%%------------------------------------------------------------------------------%%%
%%% Begin the document %%%
%%%------------------------------------------------------------------------------%%%

\begin{document}

%%%--------------------------------------------------------------%%%
%%% Document preparations %%%
%%%--------------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Preferences for Knitr %%%
%%%-------------------------------------------------%%%

<<global_knitr_options, child='usr/subdocuments/osp_global_knitr_options.Rnw', eval=TRUE>>=
@

%%%--------------------------------------------------------------%%%
%%% Document content %%%
%%%--------------------------------------------------------------%%%
%%
%

%%%-------------------------------------------------%%%
%%% Include header %%%
%%%-------------------------------------------------%%%

<<subdoc_content_header, child='usr/subdocuments/osp_header.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include abstract %%%
%%%-------------------------------------------------%%%

<<subdoc_content_abstract, child='usr/subdocuments/osp_abstract_section.Rnw', eval=T>>=
@
% Second rule which closes the title header
\ospTitleRule

% Start column layout %
\begin{multicols}{\ospColumnCount{}}

%%%-------------------------------------------------%%%
%%% Include introduction %%%
%%%-------------------------------------------------%%%

<<subdoc_content_introduction, child='usr/subdocuments/osp_introduction_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include material and methods %%%
%%%-------------------------------------------------%%%

<<subdoc_content_material_methods, child='usr/subdocuments/osp_material_methods_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include results %%%
%%%-------------------------------------------------%%%

<<subdoc_content_results, child='usr/subdocuments/osp_results_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include discussion %%%
%%%-------------------------------------------------%%%

<<subdoc_content_discussion, child='usr/subdocuments/osp_discussion_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include acknowledgements %%%
%%%-------------------------------------------------%%%

<<subdoc_content_acknowledgement, child='usr/subdocuments/osp_acknowledgements_section.Rnw', eval=T>>=
@

%%%-------------------------------------------------%%%
%%% Include the bibliography %%%
%%%-------------------------------------------------%%%

<<options_bibliography, child='usr/subdocuments/osp_bibliography_section.Rnw', eval=T>>=
@

%% End column layout
\end{multicols}

%%%------------------------------------------------------------------------------%%%
%%% End of document %%%
%%%------------------------------------------------------------------------------%%%

\end{document}
