%%%-------------------------------------------------%%%
%%% Sub document for material and methods %%%
%%%-------------------------------------------------%%%

\section{Material And Methods}

% Remove the lipsum and example table fill in your material and methods text here


\lipsum[1] 


\ospFrameMap[map=usr/graphics/MapPelargoniumSidoides.pdf,pic=usr/graphics/Pelargoniumsidoides.png,spe=Pelargonium sidoides,lab=fig:KaplandPelargonie]{Verbreitung von Pelargonium sidoides. Die Karte wurde aus Angaben der Global Biodiversity Information Facitily Datenbank erstellt. Die Verbreitung ist auf Gebiete in Lesotho und Südafrika beschränkt (Rot).}


% example for a one column table %

\begin{table}[H] % {{{
% Label tab:test_table_one
	\centering
	\label{tab:test_table_one}
	\caption{Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
	 commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis
	 dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec,
	 pellentesque eu, pretium quis, sem.}
	   {\small
			\begin{tabular}{p{0.055\columnwidth}p{0.055\columnwidth}p{0.055\columnwidth}p{0.055\columnwidth}p{0.055\columnwidth}p{0.055\columnwidth}p{0.055\columnwidth}p{0.055\columnwidth}p{0.055\columnwidth}}
				\toprule
					A & B & C & D & E & F & G & H & I\\ 
				\midrule
					1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\ 
					1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\ 
					1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\ 
				\bottomrule
			\end{tabular}
		}
\end{table} % }}}


\lipsum[1] 


\ospDFrameMap[map=usr/graphics/MapPelargoniumSidoides.pdf,pic=usr/graphics/Pelargoniumsidoides.png,spe=Pelargonium sidoides,lab=fig:KaplandPelargonie]{Verbreitung von Pelargonium sidoides. Die Karte wurde aus Angaben der Global Biodiversity Information Facitily Datenbank erstellt. Die Verbreitung ist auf Gebiete in Lesotho und Südafrika beschränkt (Rot).}
